name: Publish site
description: Publish your site to a website
icon: upload-cloud
author: a-rvid

# dry_run makes it not write on the server.
inputs:
  dry_run:
    description: "Run and authenticate, but never write or remove."
    required: false
  url:
    description: "URL to send the data"
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy.sh 
      env:
        URL: ${{inputs.url}}
        DRY_RUN: ${{inputs.dry_run}}
        TARGET: site/
      shell: bash
