name: Publish site
description: Publish your site to a website
author: a-rvid
branding:
  icon: upload-cloud
  color: white

inputs:
  url:
    description: "URL or IP to send the data"
    required: false
  ip:
    description: "IP to send the data"
    required: false
  privkey:
    description: "Client Private key"
    required: false 
  cert:
    description: "Client certificate (pubkey)"
    required: false
  dir:
    description: "The directory to publish"
    required: true
  port:
    description: "SSH Port, default 2222"
    required: false
  user:
    description: "SSH User, default root"
    required: false
  webdir:
    description: "Output website directory, default /var/www/html"
    required: false

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy.sh 
      env:
        URL: ${{inputs.url}}
        IP: ${{inputs.ip}}
        TARGET: ${{inputs.dir}}
        PRIVKEY: ${{inputs.privkey}}
        CERT: ${{inputs.cert}}
        PORT: ${{inputs.port}}
        USR: ${{inputs.user}}
        WEBDIR: ${{inputs.webdir}}
      shell: bash
