name: Publish site
description: Publish your site to a website
author: a-rvid
branding:
  icon: upload-cloud
  color: white

# dry_run makes it not write on the server.
inputs:
  dry_run:
    description: "Run and authenticate, but never write or remove."
    required: false
  insecure: 
    description: "Allow self-signed certificates."
    required: false
  url:
    description: "URL to send the data"
    required: true
  privkey:
    description: "Client Private key"
    required: true
  cert:
    description: "Client certificate (pubkey)"
    required: true
  dir:
    description: "The directory to publish"
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy.sh 
      env:
        INSECURE: ${{inputs.insecure}}
        URL: ${{inputs.url}}
        DRY_RUN: ${{inputs.dry_run}}
        TARGET: ${{inputs.dir}}
        PRIVKEY: ${{inputs.privkey}}
        CERT: ${{inputs.cert}}
      shell: bash
