# EXAMPLE WORKFLOW
name: Deploy

on:
  workflow_dispatch:
    inputs:
      dry_run: 
        description: "Dry run"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: publish-site
        uses: ./
        with:
          dir: site/
          dry_run: ${{ inputs.dry_run }}
          url: https://localhost.rvid.eu/
          privkey: ${{ secrets.PRIVKEY }}
          cert: ${{ secrets.CERT }}